version: "2"

services:
  ss-server:
    build:
      context: ./ss-server
    ports:
      - 65000-65200:65000-65200
      - 6002:6002
      - 8088:80
    volumes:
      - ./config:/root/.ssmgr
    restart: always